### ISSUE TITLE
Completion of Assignment 5

### ISSUE THREAD

**Issue by liliana-krp** [liliana-krp/Assignment-5#1]
Hi Mark,

I hope I covered the bases needed for Assignment 5. If not, please let me know.

I first worked on getting directories, libraries, and data sources set up. I then plotted length and weight with each other to see their relationship in an exploratory figure. Then, I was interested in the potential linear relationships and differences between sexes for my expository figure.

Please let me know if there is anything additional I need to do for this assignment.

Thank you!

**Comment by mdscheuerell** [comment]
Looks great, Liliana! Well done.
